config/routes.rb
Rails.application.routes.draw do
  resources :rocks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rock.rb
class Rock < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rocks_controller.rb
class RocksController < ApplicationController
  before_action :set_rock, only: %i[ show edit update destroy ]

  # GET /rocks or /rocks.json
  def index
    @rocks = Rock.all
  end

  # GET /rocks/1 or /rocks/1.json
  def show
  end

  # GET /rocks/new
  def new
    @rock = Rock.new
  end

  # GET /rocks/1/edit
  def edit
  end

  # POST /rocks or /rocks.json
  def create
    @rock = Rock.new(rock_params)

    respond_to do |format|
      if @rock.save
        format.html { redirect_to rock_url(@rock), notice: "Rock was successfully created." }
        format.json { render :show, status: :created, location: @rock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rocks/1 or /rocks/1.json
  def update
    respond_to do |format|
      if @rock.update(rock_params)
        format.html { redirect_to rock_url(@rock), notice: "Rock was successfully updated." }
        format.json { render :show, status: :ok, location: @rock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rocks/1 or /rocks/1.json
  def destroy
    @rock.destroy

    respond_to do |format|
      format.html { redirect_to rocks_url, notice: "Rock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rock
      @rock = Rock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rock_params
      params.require(:rock).permit(:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rocks_helper.rb
module RocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GriffinrocksServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rocks/_form.html.erb
<%= form_with(model: rock, local: true) do |form| %>
  <% if rock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rock.errors.count, "error") %> prohibited this rock from being saved:</h2>

      <ul>
      <% rock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rocks/edit.html.erb
<h1>Editing Rock</h1>

<%= render 'form', rock: @rock %>

<%= link_to 'Show', @rock %> |
<%= link_to 'Back', rocks_path %>

app/views/rocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rocks</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rocks.each do |rock| %>
      <tr>
        <td><%= rock.image %></td>
        <td><%= link_to 'Show', rock %></td>
        <td><%= link_to 'Edit', edit_rock_path(rock) %></td>
        <td><%= link_to 'Destroy', rock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rock', new_rock_path %>

app/views/rocks/new.html.erb
<h1>New Rock</h1>

<%= render 'form', rock: @rock %>

<%= link_to 'Back', rocks_path %>

app/views/rocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @rock.image %>
</p>

<%= link_to 'Edit', edit_rock_path(@rock) %> |
<%= link_to 'Back', rocks_path %>